services:
  postgresdb:
      image: postgres
      container_name: postgresdb
      hostname: postgresdb
      restart: always
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=28122003
        - POSTGRES_DB=laundry_system_db
      volumes:
        - ./postgresql/laundry_system_db:/var/lib/postgresql/data
      networks:
        shared_net:
  laundry_system:
    container_name: laundry_system
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - POSTGRESQL_HOST=postgresdb
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DB=laundry_system_db
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=28122003
    volumes:
      - /opt/app/bin:/app/bin
      - /opt/app/uploads:/app/uploads
    networks:
      shared_net:
networks:
  shared_net:
